### ISSUE TITLE
include_json doesn't work for simple caser

### ISSUE THREAD

**Issue by ArpiJakab** [collectiveidea/json_spec#87]
using it with RSpec expect({:make => "Acura"}.to_json).to include_json({:make => "Acura"}.to_json)

I get error:
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib/rspec/support.rb:
86:in `block in module:Support': Expected {"make":"Acura"} to include {"make":
"Acura"} (RSpec::Expectations::ExpectationNotMetError)

am I doing something wrong?

**Comment by shekibobo** [comment]
The behavior for `include_json` will match elements that are descendants of the main JSON object, but it does not support matching itself. To check the equality of two JSON objects, use `be_json_eql` instead.
