### ISSUE TITLE
json_spec does not conform to the rspec standard of abbreviating 'equal' to 'eq'

### ISSUE THREAD

**Issue by lpil** [collectiveidea/json_spec#88]
I propose that `be_json_eql` is aliased to `be_json_eq`.

`be_json_eql` could possibly be deprecated in a future version.

**Comment by shekibobo** [comment]
Hi there! We’re doing some open source maintenance work and closing old PRs. If you would still like this PR to be merged in, please re-open it by May 17, 2017. Thanks!
